i = int(input("Give me the first number: "))
j = int(input("Give me the second number: "))
print("Thank you!")
print(f"{i} + {j} = {i + j}")
print(f"{i} - {j} = {i - j}")
print(f"{i} / {j} = {i // j}")
print(f"{i} * {j} = {i * j}")